function Output = testSingleLayerPerceptron(input, target, Model)
% testSingleLayerPerceptron(input, targets, options)
% input: Input data points used for testing
% target: Target classes corresponding to the input data points
% Model: Model returned by trainSingleLayerPerceptron
%
% Outputs
% Output: Outputs generated by the perceptron

if nargin < 3
    help('testSingleLayerPerceptron')
    return;
end

input(:,3) = -1;
Output = [];

for inp = 1:length(input)
    h = input(inp,:)*Model.Weights;
    y = activationFunction(Model.activationF,h,Model);
    Output = [Output;y];
end

end